# Generated by Django 2.2.7 on 2019-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='New', max_length=15),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
