# Generated by Django 2.2.7 on 2019-12-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='worker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Worker'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
