# Generated by Django 2.2.7 on 2019-11-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
