# Generated by Django 2.2.7 on 2019-11-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_manager_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('workplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Work_place')),
            ],
        ),
    ]
