# Generated by Django 2.2.7 on 2019-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191210_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date_end',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
