# Generated by Django 2.2.7 on 2019-11-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_job_work_place_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='workplace',
        ),
        migrations.AddField(
            model_name='work_place',
            name='worker',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
