# Generated by Django 2.2.7 on 2019-12-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191210_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='workplace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.WorkPlace'),
        ),
    ]
