# Generated by Django 2.2.7 on 2019-12-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191210_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='workplace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.WorkPlace'),
        ),
    ]
