# Generated by Django 2.2.7 on 2019-12-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191210_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.WorkPlace'),
        ),
    ]
