# Generated by Django 2.2.7 on 2019-12-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20191215_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='workplace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.WorkPlace'),
        ),
    ]
